### ISSUE TITLE
Redirection after deleting a draft.

### ISSUE THREAD

**Issue by ahmgeek** [manshar/manshar#126]
Should I be redirected to the home page after deleting a draft ?
ref: ***manshar/web-client/app/scripts/controllers/profileController.js***

```js
var deleteSuccess = function () {
  $analytics.eventTrack('Article Deleted', {
       category: 'Article'
     });
     $location.path('/');
   };
```

**Comment by ahmgeek** [comment]
shouldn't it just refresh the page at least ?

**Comment by mkhatib** [comment]
Yeah I think it shouldn't redirect and just remove the deleted article from the list. (It shouldn't even refresh).

**Comment by mkhatib** [comment]
Let me know if you'd like to take this on and try to send a pull request to fix it.

**Comment by ahmgeek** [comment]
sure, actually am working on it now.

**Comment by ahmgeek** [comment]
Disclaimer: Am not a js/angularjs professional  :dancer: 
```js
$scope.deleteArticle = function(article) {
      $scope.inProgress = 'delete';
      if ($window.confirm('متأكد من حذف المقال؟')) {
        Article.delete({ 'articleId': article.id }, {}, deleteSuccess, deleteError);
        //my humble - awesome attractive - addition
        var index = $scope.drafts.indexOf(article);
        $scope.drafts.splice(index, 1);
        //
      } else {
        $scope.inProgress = null;
      }
    };
```
it works great, only for the first deletion :smile:  , after that the delete button refuses to respond! I've tried to re query the drafts on the <code>deleteSuccess</code> method but with no success.
a refresh would solve that, but it's a very bad UX practice.
that's my first time to touch the angularjs thingy so please forgive all of my sins :pray:

**Comment by mkhatib** [comment]
This looks great. My guess the problem you are having is because of not resetting $scope.inProgress to null inside deleteSuccess and deleteError.

**Comment by ahmgeek** [comment]
Hallelujah, here you are :lollipop: you nailed it.

**Comment by mkhatib** [comment]
Do you want to try and send a pull request?
