### ISSUE TITLE
Link comments authors names to their profiles

### ISSUE THREAD

**Issue by ahmgeek** [manshar/manshar#129]
make the name of the comment author link-able, redirect to author profile.

**Comment by mkhatib** [comment]
Where do you mean, I think this is the current behavior.

**Comment by mkhatib** [comment]
Sorry I just noticed that you said the comments. Good point.

**Comment by ahmgeek** [comment]
it's my fault again, noob mistakes

**Comment by mkhatib** [comment]
No problems! Feel free to take this one on as well :smile:

**Comment by ahmgeek** [comment]
@mkhatib  very well, I will try my best.
