### ISSUE TITLE
Navigation keys scrolling

### ISSUE THREAD

**Issue by AhmedGaber** [manshar/manshar#133]
- [x] **Navigation keys scrolling is not working in any article page or the home page. I can scroll up/down using the mouse only!** 
[Edit] I have to click inside the page to control it using navigation keys, otherwise, it don't work.

**Comment by mkhatib** [comment]
Assigning this to @RashaHussein. Her latest pull request will probably fix this since she got rid of the scroller and now the scrollbar is on the body rather than another div.

**Comment by RashaHussein** [comment]
I'll fix the problems with my last pull request today and push it again. It
should fix this problem.

**Comment by mkhatib** [comment]
This has been fixed by @RashaHussein pull request #180
