### ISSUE TITLE
Articles view is not horizontally at the middle of the page

### ISSUE THREAD

**Issue by AhmedGaber** [manshar/manshar#144]
- [x] **Articles view is not horizontally at the middle of the page.**
Check this photo of the front page: 
![capture](https://cloud.githubusercontent.com/assets/2565264/5728562/e7939a4a-9b73-11e4-903b-183bf717b5a4.PNG)

**Comment by ahmgeek** [comment]
```ul.manshar-articles-list``` needs ```text-align: center;``` I guess ?

**Comment by AhmedGaber** [comment]
I think that we can find the bug in this commit by @RashaHussein:
https://github.com/manshar/manshar/commit/c70a2aa51366332be1fad7c96e50fce4694f70a7

**Comment by mkhatib** [comment]
Yeah text-align: center on .manshar-article-list seems to fix it.

**Comment by mkhatib** [comment]
One problem with the text-align center is that it'll center all the content so if a line has one or two boxes it'll center them which I don't think what we want to do.

![screen shot 2015-01-18 at 1 56 38 pm](https://cloud.githubusercontent.com/assets/2647/5794232/f0c2dece-9f19-11e4-9bdb-a5f16f845554.png)

**Comment by ahmgeek** [comment]
what about removing the ```box-sizing```   from <code> * { } </code> and applying it like that :
```
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

**Comment by mkhatib** [comment]
Thanks to @RashaHussein's math we now have a really nice to the eye centered listings across the site. Well done :+1:
