### ISSUE TITLE
Optimize signup screen

### ISSUE THREAD

**Issue by samerbuna** [manshar/manshar#145]
Profile image/Bio should not be in the signup form, otherwise users will bounce more oftn before signup.

I would also remove the name (and ask for it afterward), but that's less of an issue.

Also, why not just use Gravatar for profile images?

**Comment by mkhatib** [comment]
Just fixed this in the last release :+1: 

We're only enforcing email password and name for now (Dropping bio and avatar). We also added Facebook and Google login to help users signup quicker. 

Haven't explored using Gravatar yet, but users will now have default avatars.
