### ISSUE TITLE
Reading time in article loading

### ISSUE THREAD

**Issue by AhmedGaber** [manshar/manshar#151]
- [ ] While the article is loading, that's what I see,
![article loading](https://cloud.githubusercontent.com/assets/2565264/5835373/5e555d88-a170-11e4-8e89-1132cfc804aa.jpg)

**Comment by ahmgeek** [comment]
Just fixed it. thanks for the hint

**Comment by AhmedGaber** [comment]
My hero :kissing_closed_eyes:

**Comment by ahmgeek** [comment]
@mkhatib and this
