### ISSUE TITLE
RSS feed, also for categories

### ISSUE THREAD

**Issue by antranigv** [manshar/manshar#188]
It would be nice to have RSS/Atom feed for the website, say, for the latest, the best, etc. and also for categories. and (maybe in the future) for the users.

**Comment by mjalajel** [comment]
+1
@anasAsh Would you be interested in working on this?

**Comment by mkhatib** [comment]
Thanks for filing @antranigv we definitely wanna see this in. @anasAsh any takers? :smile:

**Comment by anasAsh** [comment]
@mkhatib am setting up the environment right now (again :d ), then will start working on this 
btw: I cant find a ticket on pivotaltracker

**Comment by mkhatib** [comment]
@anasAsh, care to try our new Docker setup for development? 
https://github.com/manshar/manshar/blob/master/DEVELOPMENT_ENVIRONMENT.md

@mohammadshamma has been working on getting this up and running and would appreciate some testing for the workflow.

**Comment by mkhatib** [comment]
We have feeds! Thanks to @mjalajel :dancer: 

* https://api.manshar.com/feed/popular.rss
* https://api.manshar.com/feed/latest.rss
* https://api.manshar.com/feed/user/1.rss
* https://api.manshar.com/feed/category/1.rss
* https://api.manshar.com/feed/topic/1.rss

We'll work on surfacing and hinting these to the browsers so they can discover the feeds - specially that these are served from the api domain.
