### ISSUE TITLE
Text wrapping not working fine with pre tags

### ISSUE THREAD

**Issue by shaer** [manshar/manshar#190]
Long lines in pre tags are trimmed, the you have to zoom out to see the complete line.

<b>Environment:</b> Firefox 36.0.4/Ubuntu

<b>Example:</b>
http://www.manshar.com/articles/509

<b>Issue</b>
![pre](https://cloud.githubusercontent.com/assets/3000288/6997382/ed11de8a-dbc1-11e4-92a8-450c62edb8ea.png)

<b>Issue after zooming out</b>
![pre_zoomed_out](https://cloud.githubusercontent.com/assets/3000288/6997383/ed2fe7a4-dbc1-11e4-9d9b-fee071ff00a7.png)

**Comment by mkhatib** [comment]
Thanks @shaer 

This is actually a side-effect of another bug where our code highlighter doesn't kick in properly. If you refresh the page it might kick in again. 

Will keep this open to address it.

**Comment by shaer** [comment]
it is working fine with me now! :dancer:

**Comment by mkhatib** [comment]
Sweet! Thanks for reporting back @shaer will close this one - I already open a different bug for the broken highlights.

Thanks @ahmedelgabri for the fix! :+1:
