### ISSUE TITLE
Upload Pictures between the lines broke with JS Error

### ISSUE THREAD

**Issue by donbassa** [manshar/manshar#198]
While i was adding a new Article .  i tried to attache a picture between the line
but it gave me some JS Errors and the Form sometimes Popups, sometimes not.

![screenshot - 05102015 - 10 54 11 am](https://cloud.githubusercontent.com/assets/9343118/7553488/20f0033c-f704-11e4-839d-18defacfe156.png)

I am using : Ubuntu - Chrome Version 42.0.2311.135 (64-bit)
Picture attached.

**Comment by zakelfassi** [comment]
It appears this comes from c147d89bf66cca896a894911c0ab89883863e075 / https://github.com/manshar/manshar/blob/master/web-client/app/scripts/app.js#L213
@mkhatib : can you confirm this is related? This is CORS related.
@donbassa : did you try on Firefox?

**Comment by donbassa** [comment]
@zakelfassi Firefox works great. maybe its a problem from my Chrome ?

**Comment by zakelfassi** [comment]
Nope; Just Chrome having more strict rules on what an XMLHttpRequest can and cannot send.
The line I referred above (213) forces the setting of an "Accept-Encoding" header. Which, I believe, is the source of the problem.

**Comment by mkhatib** [comment]
The error is unrelated to the in-ability to upload as far as I can tell. 

I see the problem on a lot of requests and we might need to be picky on what requests we set accept encoding or we are using the wrong header not sure. I haven't researched this, but I don't think this is why you are unable to upload.

Have you tried again on Chrome and faced the same error?

**Comment by mkhatib** [comment]
This should have been fixed and we no longer set the header on all requests. Please re-open if you're still seeing this.
