### ISSUE TITLE
Mobile UI Issues

### ISSUE THREAD

**Issue by moradtaleeb** [manshar/manshar#199]
Tried Manshar on mobile (iPhone5), and noticed these issues (I'll work on them):

- Listing types nav elements disappear behind the logo
- When I scroll and the types nav stick at top, I couldn't open the profile menu
- Articles with title more than 2 lines, or long slogan in home page crashing the style!
- I wrote my bio, checked my profile can't see my name. If bio is more then 3 lines I won't be able to read it
- In contributors page, names with 3 lines
- In صحة ورياضة category, the third topic is: img src=x><"<(onerror=alert(1

Let me know if you have any suggestions for the above issues.

Thanks,

**Comment by ahmgeek** [comment]
actually, Manshar gets sad every time I open it from my iphone..

**Comment by mkhatib** [comment]
Closing this after the redesign!
