### ISSUE TITLE
I can't login with facebook

### ISSUE THREAD

**Issue by afaki077** [manshar/manshar#207]
i'm trying to login to manshar using facebook but i got this error message
![manshar](https://cloud.githubusercontent.com/assets/13207479/10862749/0a010512-7fc7-11e5-93d2-59b0ba175e63.png)

**Comment by moussaoui91** [comment]
me too,
i lost my account because of this,
my account was registered with facebook auth

![errormansh](https://cloud.githubusercontent.com/assets/1637374/10865586/2daf4c32-8010-11e5-8926-3568a230b6c1.PNG)

**Comment by mkhatib** [comment]
What browsers are you guys using? It seems to be working on the latest stable Chrome.

**Comment by moussaoui91** [comment]
I am use the latest Chrome : Version 46.0.2490.80 m

**Comment by mecko** [comment]
reporting the same problem on chrome 46.0

**Comment by mkhatib** [comment]
I am investigating the cause of this, it seems other [people might be facing the same problem](https://github.com/lynndylanhurley/devise_token_auth/issues/362).

Meanwhile, you guys might be able to login to your account by using the reset password flow and using the email account on your Facebook/Google account that you originally used to login to Manshar.

**Comment by mkhatib** [comment]
I believe I managed to fix this. Can you guys try refreshing the site (Hard Refresh and Clear Cache) and try again?

**Comment by moussaoui91** [comment]
i do Hard Refresh,
facebook auth working now, thank you

**Comment by mkhatib** [comment]
Thanks @moussaoui91 for checking!
