### ISSUE TITLE
New article route throws an error if the user is not logged in

### ISSUE THREAD

**Issue by tolbahadi** [manshar/manshar#225]
Hi,

When I navigate to https://www.manshar.com/articles/new/ I get a blank page with a javascript error that says: Cannot transition to abstract state 'app'. 

I should say, I'm not logged in, so maybe that's why; but a login page should show up instead of a blank page.

Here are the steps to reproduce this error:

* Open up an incognito window (Ctrl + shift + N) -- this is to make sure you're not signed in
* Go to: https://www.manshar.com/articles/new/

The first time I noticed this is was when I clicked on the link "اكتب مقال الان" from the side menshar.org

![image](https://cloud.githubusercontent.com/assets/653088/12513717/45be861c-c0ed-11e5-8435-e53fd2c86514.png)

Let me know if you need any more details.

Thanks
Hady

**Comment by mkhatib** [comment]
@tolbahadi we no longer uses the /articles/new path to create new articles so you shouldn't see it anywhere anymore. @RashaHussein just pushed an update that redirects users to a 404 page in case they land on a wrong link.

**Comment by tolbahadi** [comment]
Then you should also update the landing page "manshar.org" to make the button "اكتب مقال الان" point to the correct url.

![image](https://cloud.githubusercontent.com/assets/653088/12554812/3f02244e-c34c-11e5-8dbb-34e090766c36.png)
