### ISSUE TITLE
The main font 

### ISSUE THREAD

**Issue by MrXeious** [manshar/manshar#229]
I think (as a UI designer) the main font is a little bit old fashion and It's gonna be great if it'd be 'Greta' or any new fontface :)

**Comment by mkhatib** [comment]
Thanks @MrXeious for the bugs, we'll continue working on improving the overall design of Manshar. However, so far we're pretty happy with the font-face until we find a better open alternative. See the old [discussion about finding a good Arabic font for Manshar](https://goo.gl/l1u0eT) early on.

If you have any suggestions please let us know. Meanwhile will close this.
