### ISSUE TITLE
the ability to write code please?

### ISSUE THREAD

**Issue by lordadamson** [manshar/manshar#234]
Manshar is AWESOME.
It's missing the most important thing for me. being able to insert code.

Could that be added at some point?
Maybe as an extension? are there extensions on manshar?

**Comment by mkhatib** [comment]
Yes, we had it in our old editor and the new editor has some support for one-liners. I just created an [issue under the editor we're using to track it there](https://github.com/manshar/carbon/issues/59).

Thanks for filing, will close this one and track adding code feature there.

Meanwhile, one thing you can actually do currently in Manshar is to embed different sites, including some code-sharing sites like (codebin.io, pastebin.com, jsfiddle.net, jsbin.com) and it works pretty well, try it out. I [embedded a jsfiddle for example in my article about building the editor](https://www.manshar.com/articles/2905/). We have an improvement for embedding sizing and loading coming up to the next release.

Glad you liked Manshar :smile:

**Comment by lordadamson** [comment]
Thank you! looking forward to seeing the feature implemented.
