### ISSUE TITLE
Broken API/ trouble accessing my Manshar account

### ISSUE THREAD

**Issue by azzenovic** [manshar/manshar#282]
Hi! Recently, I haven't been able to access my manshar account. Actually , last year I signed up to manshar using my Facebook account details and everything used to work fine. I attached a screenshot of the error I get . 
![manshar](https://cloud.githubusercontent.com/assets/5151198/23379545/9afed096-fd37-11e6-8031-4abc4dd9a10d.png)
P.S : I am using firefox

**Comment by mkhatib** [comment]
Hey @azzenovic we had issues with cloudflare and heroku a few days ago not serving the correct HTTPS. 

Can you make sure to go to https://manshar.com and try to clear the cache and see if things work? 

When do you get this error? I am happy to jump on a video call to debug this with you if you have some time? I can be found here: https://appear.in/debug-manshar

**Comment by mkhatib** [comment]
Thanks @azzenovic for the call! This should now be fixed! 

Apologies! It seems that this was broken by a change in the gem we're using for authentication: https://github.com/lynndylanhurley/devise_token_auth/issues/832

**Comment by azzenovic** [comment]
@mkhatib glad to hear that :) ur welcome! looking forward to improving Manshar . See you soon!
