### ISSUE TITLE
Cann't reset my password

### ISSUE THREAD

**Issue by ahmedissa** [manshar/manshar#287]
i get this error msg when i open the reset link.

Cannot GET /accounts/update_password?client_id=xxxx&config=default&expiry=&reset_password=true&token=xxxxx&uid=xxx%40gmail.com

**Comment by mkhatib** [comment]
@ahmedissa thanks for filing and sorry for the inconvenience. Just pushed a new update that will fix the bug. Please try again.

**Comment by ahmedissa** [comment]
thanks it works now. But i get error msg when i submit a password with length <= 7.   the error doesn't explain the reason behind it.
![bildschirmfoto 2017-03-15 um 13 32 08](https://cloud.githubusercontent.com/assets/2643942/23949492/bbebb04c-0987-11e7-880a-52945b103704.png)

Debug:
`
{"success":false,"errors":{"password":["أقصر من اللّازم (الحد الأدنى هو 8 حروف)"],"full_messages":["Password أقصر من اللّازم (الحد الأدنى هو 8 حروف)"]}}
`
