### ISSUE TITLE
Update: the article was published later

### ISSUE THREAD

**Issue by azzenabidi** [manshar/manshar#288]
Hi @mkhatib  I have recently published an article on Manshar. Though the article is marked as published, it doesn't show up neither in the stats section nor in the latest section.

For more info, please check the attached screenshots . Thanks!
P.S: On august 21th, I was surprised to find notifications. my article was finally published . 

I hope we find out the reason behind this delay.

![notif](https://user-images.githubusercontent.com/5151198/29508520-c5d96440-864c-11e7-8845-ef58b30cb245.png)

![bugthree](https://user-images.githubusercontent.com/5151198/29495947-bedc378a-85c0-11e7-8263-00444d410c73.png)

![bug-two](https://user-images.githubusercontent.com/5151198/29495948-bee3e78c-85c0-11e7-8514-0f35c26f7bd7.png)

![bug](https://user-images.githubusercontent.com/5151198/29495949-bef380e8-85c0-11e7-88c0-216e003ff272.png)

**Comment by mkhatib** [comment]
Thanks for Filing @azzenovic. Our workers were having problem running, fixed them and now should be able to show the articles. Please re-open if you're still seeing an issue.
