### ISSUE TITLE
For anyone looking for the data

### ISSUE THREAD

**Issue by ahyield** [manshar/manshar#289]
I made the `published` articles available here: [https://github.com/ahmgeek/manshar-data](https://github.com/ahmgeek/manshar-data)

**Comment by 0xMH** [comment]
Is it still available? There was one of my precious articles in manshar but I can't find it anywhere.

**Comment by ahyield** [comment]
Hey everyone, am sorry, I took my repo down due to EU/GDPR regulations.
Please send me an email if you want the data: `ahmgeek @ icloud [dot] com`

**Comment by abusalmanpedang-png** [comment]
مرحبا
