### ISSUE TITLE
Fix Chrome No 'Access-Control-Allow-Origin' Error

### ISSUE THREAD

**Issue by lambdaX** [manshar/manshar#47]
During signing up and submit to http://api.manshar.com/api/v1/registrations.json request  fails with Google Chrome.

**Comment by saada** [comment]
This has to do with the web server configuration. I'll try to make pull request to fix this.

**Comment by saada** [comment]
Technically this shoulda fixed it:
https://github.com/manshar/manshar/blob/master/backend/config/environments/development.rb#L63

**Comment by mkhatib** [comment]
I haven't seen any errors with this recently, so closing this for cleanup. If you still see this issue please re-open.
